### ISSUE TITLE
Compat with yucca bundles atmospheric?

### ISSUE THREAD

**Issue by thelegitdolt** [davidjjung/gravitygourds#2]
That would be pretty cool in my opinion since those already fall

**Comment by davidjjung** [comment]
Those already break into individual yucca fruit upon falling onto *any* non-full-face blocks like pointed dripstone, torches, etc. I can basically add the audiovisual effects, but it'd be slightly inconsistent with melons/pumpkins since it'd "split" into fruit under a larger set of conditions. lmk what you think 👍

**Comment by thelegitdolt** [comment]
I think i would do full parity, make them have the exact same falling behavior as melon and pumpkins, since they're pretty similar. It would also be cool to make melons and pumpkins do damage to you if they fall on your head, like yucca bundles.
